databases:
  - name: backenddb
    plan: free
    databaseName: backend
    user: mangos

services:
  - type: web
    plan: free
    name: backend
    runtime: python
    rootDir: backend       # <--- add this
    buildCommand: 'cd backend && ./build.sh'
    startCommand: 'cd backend && python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backenddb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4